### ISSUE TITLE
Build failure for cxf-jaxrs-xmlsecurity

### ISSUE THREAD

**Issue by allancth** [coheigea/testcases#10]
Hi,

I am having problem building the project, with the following errors:
  testXMLEncryptionDOM(org.apache.coheigea.cxf.jaxrs.xmlsecurity.xmlencryption.XMLEncryptionDOMTest): java.lang.RuntimeException: Illegal key size, stacktrace: org.apache.xml.security.encryption.XMLEncryptionException: Illegal key size(..)
  testXMLEncryption[9002:dom](org.apache.coheigea.cxf.jaxrs.xmlsecurity.xmlencryption.XMLEncryptionInteropTest): java.lang.RuntimeException: Illegal key size, stacktrace: org.apache.xml.security.encryption.XMLEncryptionException: Illegal key size(..)
  testXMLEncryption[9003:dom](org.apache.coheigea.cxf.jaxrs.xmlsecurity.xmlencryption.XMLEncryptionInteropTest): java.lang.RuntimeException: Illegal key size, stacktrace: org.apache.xml.security.encryption.XMLEncryptionException: Illegal key size(..)
  testXMLEncryption[9002:streaming](org.apache.coheigea.cxf.jaxrs.xmlsecurity.xmlencryption.XMLEncryptionInteropTest): org.apache.cxf.interceptor.Fault: No message body writer has been found for class org.apache.coheigea.cxf.jaxrs.xmlsecurity.common.Number, ContentType: application/xml
  testXMLEncryption[9003:streaming](org.apache.coheigea.cxf.jaxrs.xmlsecurity.xmlencryption.XMLEncryptionInteropTest): org.apache.cxf.interceptor.Fault: No message body writer has been found for class org.apache.coheigea.cxf.jaxrs.xmlsecurity.common.Number, ContentType: application/xml
  testXMLEncryption(org.apache.coheigea.cxf.jaxrs.xmlsecurity.xmlencryption.XMLEncryptionStaxTest): org.apache.cxf.interceptor.Fault: No message body writer has been found for class org.apache.coheigea.cxf.jaxrs.xmlsecurity.common.Number, ContentType: application/xml

**Comment by coheigea** [comment]
You need to install the unlimited strength security jars in your JDK.

**Comment by allancth** [comment]
Noted with thanks.
