### ISSUE TITLE
Using santuario in android

### ISSUE THREAD

**Issue by josecostamartins** [coheigea/testcases#12]
I'm having major trouble making santuario work with android, the problem is (probably) that the stax api is a core part of the Java JDK (JVM) but not the Dalvik Virtual Machine (which is the VM that runs android code).

Is there anyway I can use apache santuario with android?
OR
Is there a way for me to get the santuario lib without stax?

Thanks in advance

**Comment by coheigea** [comment]
You could try using an older version of Santuario that doesn't support StAX (e.g. 1.5.8).
