### ISSUE TITLE
kinit: krb5_get_init_creds: unable to reach any KDC in realm kafka.apache.org, tried 1 KDC

### ISSUE THREAD

**Issue by natedogs911** [coheigea/testcases#14]
I'm trying to verify that the KDC is working by setting KRB5_CONFIG to the key tab generated for client.

Is the password definable to verify manually without -kt?

EDIT:

to be clear, following this [example](http://coheigea.blogspot.com/2017/05/securing-apache-kafka-with-kerberos.html)

**Comment by coheigea** [comment]
What's the problem here exactly? Yes, you can just do "kinit client" and then specify the password as prompted.

**Comment by natedogs911** [comment]
basically I'm running the bigdata-kerberos-deployment kafka test example,
It's not clear to me what the password would be. is there some code generating the password?

**Comment by coheigea** [comment]
The password is specified in the test code here "client":

https://github.com/coheigea/testcases/blob/8a24caf7b0def2222fd0866a53da4e802ecaa711/apache/bigdata/kerberos/src/test/java/org/apache/coheigea/bigdata/kerberos/kafka/KafkaKerbyTest.java#L78

**Comment by natedogs911** [comment]
ah ok, I tried client but no luck

**Comment by natedogs911** [comment]
kinit client
client@kafka.apache.org's password: 
kinit: krb5_get_init_creds: unable to reach any KDC in realm kafka.apache.org, tried 1 KDC

I'm thinking this is likely network related?

**Comment by natedogs911** [comment]
not sure if you want the whole maven log,

```
 T E S T S
-------------------------------------------------------
Running org.apache.coheigea.bigdata.kerberos.kafka.KafkaKerbyTest
KDC ready on port: 63119

```

**Comment by coheigea** [comment]
Are you setting KRB5_CONFIG to point to the krb5.conf in the target directory?

**Comment by natedogs911** [comment]
yes, I can tell it's getting the information from the krb5.conf since it's trying the correct realm.

**Comment by natedogs911** [comment]
if I can get this working, my intention is to orchestrate this with some scripts to test a python framework

**Comment by coheigea** [comment]
What platform are you on? You could also try setting the Java system property "sun.security.krb5.debug" to true on the Kerby side to give more detailed output.

**Comment by natedogs911** [comment]
@coheigea I found the issue,

first to answer your question I'm on Mac OS X 10.13 (17A405).

the issue was at [kerbyServer.setAllowUdp(false)](https://github.com/coheigea/testcases/blob/8a24caf7b0def2222fd0866a53da4e802ecaa711/apache/bigdata/kerberos/src/test/java/org/apache/coheigea/bigdata/kerberos/kafka/KafkaKerbyTest.java#L58)

by setting it to true this resolved the issue.
it's been a while but I think that this has to do with the apple version of kinit if I remember, but I could be wrong.
