### ISSUE TITLE
put username & password in client dynamic 

### ISSUE THREAD

**Issue by mmirzaeyan** [coheigea/testcases#6]

**Comment by coheigea** [comment]
Care to expand?

**Comment by mmirzaeyan** [comment]
In cxf with spring security you used username and password attribute for pass it to the service from the client, i wanted to add them dynamically, for that i make outinterceptor and extends from serviceinvoke interceptor and it's worked , i want to know your idea about that

**Comment by coheigea** [comment]
In the examples, the username is set dynamically by setting a configuration property on the client request context. Personally I would prefer this approach than adding a custom Interceptor, but whatever works for you...
